#!/bin/bash
sudo chown ec2-user -R /var/www/html/wp-content/themes/vmturbo
sudo chgrp apache -R /var/www/html/wp-content/themes/vmturbo
sudo chmod -R 755 /var/www/html/wp-content/themes/vmturbo
rm -f /var/www/html/wp-content/themes/vmturbo/appspec.yml
rm -f /var/www/html/wp-content/themes/vmturbo/before_install
rm -f /var/www/html/wp-content/themes/vmturbo/after_install
