#!/bin/bash
cp -r /var/www/html/wp-content/themes/vmturbo /var/www/html/wp-content/themes/vmturboOLD
rm -rf /var/www/html/wp-content/themes/vmturbo
mkdir /var/www/html/wp-content/themes/vmturbo
cp -r /var/www/html/wp-content/themes/vmturboOLD/dist /var/www/html/wp-content/themes/vmturbo/dist
cp -r /var/www/html/wp-content/themes/vmturboOLD/.git /var/www/html/wp-content/themes/vmturbo/.git
cp -r /var/www/html/wp-content/themes/vmturboOLD/bower_components /var/www/html/wp-content/themes/vmturbo/bower_components
cp -r /var/www/html/wp-content/themes/vmturboOLD/node_modules /var/www/html/wp-content/themes/vmturbo/node_modules
